### PR TITLE
added a task input component

### PR DESCRIPTION
**Pull request by gxc19**
I have created a task input component which allows the user to type a task, in which it will print underneath

### CODE REVIEW

**Comment by liamsouthall** [comment]
Looks ok

**Comment by ross-burrows** [comment]
looks good nice work mate

**Comment by johnmuir2001** [comment]
not bad but it will have to do

**Comment by mclarework** [comment]
Looks good, but I have been lost on the server all morning, so I am not the best person to make a merge decision...

Will update my front end code and try to stay on top of it more moving forward.

**Pull request merged**
